### ISSUE TITLE
Rewrite History

### ISSUE THREAD

**Issue by renatovico** [raphaelcosta/braspag-pagador#1]
Hi

I'm the developer of this branch, unfortunately i don't have time for finish this work, and first great thanks for keep maintain ! 

Only when your mention this is based on work of codeminer42, it's not right, the first start project is gonow with (@drec18, @ricardoalmeida) , after forked by me, @lenonmarcel, @tinogomes, @madsoncardo, @lucabastos, @cassiomarques, and after used by codeminer42 and re-again forked by @vinicusbaggio, after this point, i rewrite all code based in active merchant approach.

**Comment by raphaelcosta** [comment]
Fixed! Thanks Renato!
