### ISSUE TITLE
Erro em homologação

### ISSUE THREAD

**Issue by ricardopacheco** [raphaelcosta/braspag-pagador#4]
Olá,

Estou usando a gem e adicionado o merchant_id gerado na sandbox que o braspag me forneceu. Usei o código parecido com o do README só que sempre aparece isso:

StandardError: {"amount"=>"10.00", "number"=>nil, "message"=>"Merchant is not available for transaction", "return_code"=>"146", "status"=>nil, "transaction_id"=>nil}

Não consegui encontrar esse erro na documentação da API.

**Comment by raphaelcosta** [comment]
@ricardopacheco conseguiu resolver esse problema? Era algo com a Gem?

**Comment by ricardopacheco** [comment]
@raphaelcosta sai da comunicação por webservice e fui para API @raphaelcosta.
