### ISSUE TITLE
Função GetJustClickKeyRequest 

### ISSUE THREAD

**Issue by rmomogi** [raphaelcosta/braspag-pagador#6]
Eu cheguei a implementar a função GetJustClickKeyRequest. Gostaria de incluir no projet ou alguém posso adicionar essa função. Segue os códigos em anexo.

File: recurency_credit_card.rb

```
def get_just_click_key(request_id)
      response = self.soap_request(:get_just_click_key, request_id)
      status = response[:success]

      ActiveMerchant::Billing::Response.new(status,nil,response,:test => homologation?)
    end
```

File: core/connection.rb (Linha 69)

```
when :get_just_click_key
        protected_card_url + "/CartaoProtegido.asmx?wsdl"
```

Aguardo a ajuda!

**Comment by raphaelcosta** [comment]
@rmomogi faz um Fork e abre um Pull Request dessas alterações
